### ISSUE TITLE
[Feature Request] GitHub スター数によるソート

### ISSUE THREAD

**Issue by sprout2000** [kurehajime/jimoto_no_github_user#2]
いつも便利に利用させていただいております。ありがとうございます。
地元のユーザーを獲得している GItHub スター順でソートも出来るようにしていただけると助かります。
何卒ご検討いただけますようお願い申し上げます。

**Comment by kurehajime** [comment]
ご利用ありがとうございます～

スター数順でのソートは自分も実装したいのですが、Githubの検索APIがその順番でのソートを提供しておらず、難しいんですよね…。

**Comment by sprout2000** [comment]
ご返答ありがとうございます！

> スター数順でのソートは自分も実装したいのですが、Githubの検索APIがその順番でのソートを提供しておらず、難しいんですよね…。

そうなのですね。残念です。
ご回答いただきありがとうございました。
